apiVersion: oidc.orchestrate.cloud.sap/v1alpha1
kind: KubeConfigGenerator
metadata:
  name: example-kubeconfig
spec:
  forProvider:
    kubeconfigTemplate:
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: kyma-connection-secret
        key: kubeconfig
    oidcToken:
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: oidc-token
        key: IDToken
  writeConnectionSecretToRef:
    name: kubeconfig-published
    namespace: crossplane-system
