# This workflow is triggered by the user and runs the REUSE compliance check (reuse lint) on the repository.

name: REUSE Compliance Check

on: 
  workflow_dispatch:
  workflow_call:
      

jobs:
  lint-reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@3ae3c6bdf1257ab19397fab11fd3312144692083 # v4.0.0