# This workflow is triggered by the user and runs the REUSE compliance check (reuse lint) on the repository.

name: REUSE Compliance Check

on: 
  workflow_call:
      

jobs:
  lint-reuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@3ae3c6bdf1257ab19397fab11fd3312144692083 # v4.0.0